In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(-90,90, size =1500)
lngs = np.random.uniform(-180-180, size=1500)
lat_lngs = zip(lats, lngs)
lat_lngs

In [3]:
# Add the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

In [4]:
# Use the print() function to display the latitude and longitude combinations.
for coordinate in coordinates:
    print(coordinate[0], coordinate[1])

75.52651423208187 -67.80086488147708
61.546903506626506 -322.78660316712677
36.76775927645345 -292.8880210744742
57.69131281602077 -172.01312144094973
0.6295955673013793 -2.436536765722906
-63.40503904104882 -265.5360230617078
-29.548313760543294 -17.47821233185539
-60.0377461615674 -76.18346278642997
-32.93652975096072 -327.10997962931117
-79.99231631680807 -152.45390351228284
11.160897825125872 -195.05888062481677
-36.25660396793801 -300.5729352867936
-11.307821820072249 -187.86183855017237
0.07951071204311688 -204.6867240317731
34.355679683854206 -214.1859322172793
-32.180473776777674 -225.9470576968452
-21.766587873194766 -284.6252286613392
0.6776698152287395 -6.908557338968137
78.77206491282999 -88.31154854799337
-6.600721455820604 -80.1865480299216
-74.6448080828705 -338.4026927658477
37.5511063043225 -310.7175473862029
6.98115720541665 -294.4332109223406
81.10812980870526 -276.49994214215565
-59.2868453091304 -118.21190470711014
49.75502149274158 -312.66064950401227
88.99392525604435 -84.98869351410065
-18.02914014335842 -18.894929662672837
61.81970427048526 -303.61038862420685
87.25223209800859 -220.16737950481027
-21.913466963168744 -237.39188052268992
0.9718212144920102 -194.1588022794385
-88.27918760134843 -72.33333606455619
-18.500458173019325 -182.44728448735285
-23.630952237782154 -302.9303416032802
4.292677389789603 -87.23624414617007
-75.20484026901158 -183.7438225059586
75.05025862590068 -218.75299785078985
-10.369942146603591 -134.67179841569288
-7.779914494704244 -158.03320264596644
34.81257907897643 -60.52208925191127
-43.99033916307592 -302.11153184304186
27.905574249615682 -58.788714171622985
-47.49818755585397 -24.30465517675526
27.846429823432118 -223.2896148363082
23.148588234703595 -16.636075119338273
28.040537002031684 -276.4525352344589
-76.34525560437142 -179.97293330495114
72.80190393239462 -26.66923596778264
38.667444060016464 -48.5313370300201
-39.440209319179715 -32.713657646620106
-37.346567985310564 -114.02101823733503
56.070067177501045 -95.24034778381338
23.49021880555229 -60.99498053340483
-87.02694782976974 -245.69829460526893
82.98663113638256 -63.76236933413924
34.48549275830807 -40.05700721418776
-89.33095734001235 -293.16390078472716
35.803373195317675 -224.16302084616004
-31.57606516992928 -223.85119662109895
-50.38607113510416 -303.4194472171863
70.68786303817319 -266.41331525531456
2.7623456016100363 -342.5780806859893
61.272990553031065 -191.88364806258122
-4.4176725797996 -62.261317426025016
-31.72913297426379 -265.393555195501
-73.93013970259763 -264.5922658929664
-58.239749353617015 -121.30688183814999
-52.79626366356789 -34.16911729309726
-67.50336331916745 -160.93262763507516
-63.811755853679855 -347.7922023200992
-54.08886114327681 -289.25923677797294
-44.73604936982795 -170.34350587390088
58.12592421374222 -217.03818420094385
35.59000059177208 -280.6711011697741
59.58423461716646 -260.3668500297491
-41.51693930724474 -42.598121999797286
-73.06138048330226 -49.837740144419
-31.513260129483605 -33.157936130410235
21.77658075335802 -287.4035370128147
-72.25299283929238 -54.21017449703106
59.4386726687884 -246.49854425421682
-2.2337343647754153 -64.52009109859972
58.893194975057185 -88.54047173705874
-45.33184843452611 -137.610785590852
-2.464275066252071 -114.8464419472183
-82.20654079320877 -183.50676360277598
-10.638549673781341 -93.70558607759273
-61.23622436695686 -272.36338329895864
40.10466583809037 -155.08255313367647
-21.50633781080687 -125.81989785214714
-28.2743196316271 -201.4990657376767
-52.42690854323032 -34.60432626792857
-25.52541212536653 -193.16914284476164
65.21041485179148 -128.80423694061503
1.4889078567408234 -117.97411213592491
53.93359777312634 -288.6368340093777
74.27176451321955 -203.72481620206716
67.40820482199891 -107.63783820992467
-85.76243574319214 -293.5338184035136
51.682922965025284 -10.825947259319321
-17.161275349506056 -353.9431002878865
-1.9791913369097642 -40.513583900139906
-27.8688426583114 -290.18829741274635
-33.308661197950336 -76.88968433329865
49.281794058253126 -297.1456027721289
-57.38050129992286 -314.2404349521993
-15.295850994270495 -192.45992164098752
-84.54532305093639 -349.41171492057686
74.22192276708313 -49.52875373741716
47.92926949065293 -110.3710764610095
-32.84074870239082 -314.71320935353395
43.12448299134613 -311.4010000584577
-52.89813363413918 -202.3070308480605
15.249410967759786 -60.855022681862295
2.1857670721338707 -277.6070746309457
-56.28330591285888 -202.87998412474016
-36.47748822874159 -52.71161266977941
86.6968780812617 -104.27250301245294
29.225680732199777 -85.95264812500511
19.23572731476483 -98.13464391096164
6.761823113435312 -332.46343698460953
-45.44104368790514 -335.291522627513
-37.00403119697919 -57.31290190769619
-35.23375103412293 -320.3548180659795
46.53258990282987 -319.53850362625474
7.968699374457529 -352.73465405800505
41.3722800717691 -7.118566102997306
-46.51086563853991 -222.72563057697923
45.181221137473045 -133.66967472332007
-39.73769076678349 -35.946062724226294
-80.90862146873181 -305.4536649814356
-19.852032987118548 -359.47027862152413
86.78691829402004 -77.72088355586914
18.25477789563739 -336.94967661296164
-55.61443371555812 -216.57647401569292
-19.328354296949016 -189.79628317621467
22.785069715840592 -237.23582108601317
-42.696368833358726 -252.90180504384878
-57.415002390022636 -1.9872270214571586
87.42574063369554 -51.222312250620746
64.09087702343251 -4.123278628345076
-75.73620537413872 -89.32800842247707
37.850484093252845 -46.86238268031542
18.627616669288358 -265.1102253333225
26.382304467539896 -130.79439599521288
-76.72100638037726 -15.646744970762768
-17.36828149834315 -55.43681712601972
89.71463382991939 -14.54664371435723
81.11904633760915 -22.31471821910901
31.565840815581254 -235.59699805253345
61.32223719315803 -48.27296960410746
17.29018861023293 -223.12498972734545
11.095145897893488 -333.9073051711207
-28.64398954889566 -237.35989932167803
-54.735323721671755 -171.11726756171686
18.696366027978968 -137.05909842815754
-44.44492638252848 -168.25031331311737
-8.912233485405736 -120.48452299044067
-73.88840877509642 -80.76783319852888
71.51012905919407 -348.60251399228196
84.61859399405898 -44.12678767086766
44.96361206219689 -270.6312697111738
18.242708697474313 -90.0038418314976
-20.11855268620974 -152.88532806666973
-5.618866533127203 -259.87702796009876
41.06782461506711 -251.41147982845536
6.254610494721575 -234.31119696499462
-49.89686864834391 -148.07243036739794
-80.03549495207734 -216.57225711610195
-31.550246379981672 -269.45779230912785
-40.82515411294012 -123.40482286284848
-24.444326911365224 -188.18931536862132
37.08343623906177 -114.7913227255014
-33.3177103618559 -2.7037602636040106
76.61282494295901 -219.80245467232515
-65.81184583223204 -180.04265375133963
-53.792931261170025 -76.7202068937064
-70.82392801411962 -220.2777154709192
28.70628141099469 -127.85192118109131
77.50606939490231 -59.79435680324201
45.334174066811414 -332.2702555863654
-57.442365126969555 -39.958703529616116
36.08216071969136 -0.057981965921271694
57.385094499077155 -300.3166350513984
88.61206940650135 -3.2746986793799238
-78.13463985120502 -170.03722299209772
36.51292667768148 -346.7278636838403
31.83827309074654 -180.85399776291595
-11.7224407149603 -108.42777383496772
83.26943560302288 -14.647502197259712
-72.32792898491924 -11.621960981760253
-63.69951019078056 -133.59803631673626
46.55958393159301 -74.86766758390212
-31.84259834550683 -101.145557468373
22.959411357916593 -101.61655300171776
-31.04694528800674 -171.28259776125253
40.23419429882421 -74.91959151004369
-87.73881689314062 -226.5543161468101
-80.17003250013747 -358.9272652948877
70.76191255379146 -267.52589600326957
-41.17817878107133 -178.7868574247111
29.59221614092553 -77.78881322889782
51.0493992086102 -76.67816027842878
74.03375402373064 -229.92602100895218
12.419903107964515 -163.2316635519744
46.335855735037995 -330.1068342751068
69.04498556277366 -117.78154760714744
73.22625636537404 -70.03609595370801
-79.03330841455622 -118.30788910505532
-70.99073126267191 -35.83215258044578
84.89825807686248 -268.09048573573887
-54.97856434358545 -349.01708647597036
-5.776367683387647 -31.367477899322466
3.9440099483121145 -134.79725285071987
-40.21539967989153 -111.14085124229723
39.97819324583895 -135.10220917039211
-12.854925942778962 -171.19184898484392
-67.29283350581181 -116.24063048021054
-20.94434523117998 -27.045553830225003
-84.78959359774679 -311.7124275454905
-33.737831357313866 -310.7556974757794
-9.582708365460974 -296.09327188882
16.5706288453907 -1.328959084578571
-44.92790824501824 -212.99134113278768
72.85928172631736 -310.02790264269754
82.80645680719994 -189.5179726365636
-36.6711723436277 -229.05286372362878
34.73532053924535 -265.55571334603565
-53.02142184356978 -177.94188888751324
-55.55625534052799 -153.85761236746674
-57.65097097338661 -343.8903374023728
82.50149354752571 -217.5149405248194
40.634297754519935 -71.79338345706651
-19.017367674773297 -206.23202248817796
13.031388961913734 -242.3289779987956
86.35293515533354 -267.97473038098826
-42.268051874782756 -279.0883295158522
-27.5455691547064 -38.93268810275492
55.92531172119254 -299.8805329201773
-65.37364975834214 -59.36666902121948
-58.45111201495948 -273.1576557850388
0.9792161709575993 -99.68961881950622
41.379404466725106 -60.373262003686534
-69.77162398101902 -91.52493486393979
-36.16672272214631 -162.23944993645122
-11.380435870387771 -144.888950408556
83.62788495471915 -64.93993154478778
16.59934313762352 -293.0646311985234
-32.0035119320232 -61.98411646070957
15.469493059362208 -336.84102055579683
-72.54397973220941 -278.3127183687818
38.317075679285296 -59.953901816794826
51.18534837692914 -99.3973901104277
-7.256139198621369 -326.62560360641965
-44.21170668934653 -143.86645473877627
-43.80751297428607 -5.139628422812166
-69.09866460792703 -238.22458255594742
0.2789413308348401 -118.89626442611058
58.658195740164416 -268.6887177719608
77.06150881581866 -131.56148377310052
-65.23729046224038 -323.8851572582497
53.464091531564975 -232.226195239442
-60.245207661079704 -155.94183335396298
85.25389801829672 -232.90776405330723
-30.85162138163804 -313.50209260353074
75.26512487818667 -67.92019837143994
57.20021334098848 -207.01705500851702
-83.41515185891015 -51.1476621860474
62.9262320201949 -304.062460895096
-53.80073832606404 -144.62418435147237
68.10841771289051 -259.93705261113377
-53.875952712613525 -138.88600128792328
-40.658090751595694 -8.578931172293323
-19.97528161847309 -150.16601377800018
-88.64069290935056 -190.81903342934564
-43.46278863493561 -207.1580095240834
31.979120585151648 -50.99108652359121
70.04208898936133 -284.4556939906525
71.43395195131379 -220.88093867722594
-56.24671076125189 -30.97188581384205
-72.70584627170575 -216.53801285183692
-30.248754696383465 -183.11136348471572
15.714731214706973 -260.58270457735995
-49.53701333543309 -221.9394145588929
-71.61996201530944 -154.8353687133799
-50.61914014712735 -98.75789770398859
-84.15777457130257 -194.94675739891412
73.71813705439104 -87.48191041686727
-4.989223798204705 -357.74825841998944
-14.389161744500697 -10.351545523664527
-68.58248797903589 -2.5873479722303045
77.27545307647193 -57.74480497898304
-79.89253784550034 -258.0757529281857
70.74531557213123 -5.0661449146394375
29.651744637713975 -277.8864637156221
-59.49979365506605 -149.57336950594726
21.236975287773575 -205.69634565233287
-11.328457856989857 -192.91347553686234
86.68191126712904 -95.36242878084698
43.71087235452404 -16.239381147701238
-25.37086872653471 -350.59801922714536
48.71622021948042 -243.28383802812652
23.49695766474879 -244.5652409604954
-28.817572242968986 -276.6699086178498
62.71358407871821 -123.08128734787988
-71.70822967602942 -23.00237512743587
-49.64921107848255 -111.42761023558486
-68.35086765389605 -33.82975151509373
79.3923213958976 -29.780795842271345
-54.172285390737315 -74.79391383653433
-89.48486506335489 -64.42247435661079
-86.92434739611178 -327.70208486389885
75.86164211344496 -46.951972625021995
-37.303271328067886 -261.2103968972568
39.662925961111256 -231.81740677897469
42.38913439015022 -193.54203396882775
-4.336606432384258 -33.48549540175196
-43.63538526415317 -115.66849555011066
-10.622256752736732 -60.85994407270118
-2.4235970153922892 -10.620239411921716
14.333171861959997 -155.60332291665023
28.162861730180595 -305.2173104338845
19.341231588850846 -219.70101705006937
33.31376412522471 -310.91722747115784
13.074542361092753 -154.40943137815265
45.22795275961553 -6.697631120678864
47.75157209864267 -76.87770426851438
17.139434273719473 -283.71570111738333
-54.34398221517889 -24.705367607328753
-2.957914235648431 -209.18520346235871
51.95465124311613 -229.96580461838727
-59.25575479360752 -97.50593607545875
17.16393814613292 -306.01970400189384
55.07836767370932 -308.1497709769411
-58.493720276032846 -155.28556518394925
65.29007462395501 -289.42869213964786
-65.52549194881537 -98.34823479082615
-72.72711753411096 -102.32181342173044
-54.691264847647275 -325.2452769359811
11.720425325302799 -168.60430777795804
-24.70572672865022 -18.978811188336806
35.33061206031739 -218.98224899666587
-48.90482244912468 -30.970431784657308
-56.38378783652441 -25.83300449187186
-50.45794902122964 -64.2005174499086
-11.535923438334393 -209.95274477522025
-42.833148345721256 -16.178611176478967
-56.04456119899846 -349.9640580486126
-37.845341107486945 -25.332953638488164
-64.29896657204574 -287.08113679977464
-32.37547898954919 -41.92648702630851
30.312514902371305 -103.77723496493769
43.8124274703558 -59.477416833676955
20.382678433004784 -4.565683582865802
44.68167203911855 -107.91419177137715
-62.90648954684124 -52.276154662258136
-43.188154991338145 -321.73332398312635
-8.194480147472106 -258.9127977384167
-33.47251485786082 0.7074848370942277
-85.62846397917582 -172.22360427236123
-62.77286737604623 -255.4106707463945
-22.657464104127314 -7.31041273238003
-89.05725148505304 -315.0112243250852
-18.62004648660715 -326.6485138184346
32.21426484516411 -329.7954236703959
-50.4078437913286 -41.18064134355785
-85.7977101890108 -52.243698340805395
-8.705232386813748 -109.10248165694819
-81.25938879620058 -309.78256851495786
-23.61309696928815 -84.08572308464778
31.011695349595882 -306.27519301999524
-64.34400954357119 -1.1990127359939606
58.38632689664169 -115.5578344789545
-56.03461323926455 -9.848408678784438
10.616901309718159 -160.88981541066002
-81.85396378286981 -105.08517096818858
-16.9660522204436 -25.65950059993753
-25.167583036336822 -136.17140195789918
46.23724782274445 -274.04886402629154
10.438855346079762 -68.32781130315249
63.32065338154973 -294.0162380503805
34.1938098602116 -329.63720886641374
-68.15309069767098 -118.3887639481452
-9.524868286249458 -250.3465257042934
-72.46496281516215 -329.56773887738814
52.166686480962085 -44.881678117384695
-71.29247175948791 -295.85164494280514
33.98685344706627 -249.59811096132643
13.398353456324955 -189.24127620432924
60.09332088487426 -128.20919295211226
-79.51799439430245 -326.5285868008467
-88.01175255691005 -178.86323375599596
68.07189063291338 -264.51108836352165
77.20602470109654 -9.542313155854515
38.30736895476437 -82.6620034889853
20.43002853834885 -283.68443472454953
-82.92719591603876 -2.095941831804396
-4.809590169937607 -358.9153470846522
82.89246260107612 -40.08050295973874
-22.075175850932283 -234.58762411051976
86.15361647811574 -356.59064845869574
54.97905098669992 -31.11340362111207
-48.62076850413618 -147.92452193592493
-23.905404881242788 -41.90786132708297
-1.0559009654793812 -339.129077856536
57.9685092746372 -289.51040855503703
2.52700587740091 -316.0806416137492
-10.042158551219558 -145.81863218388912
-27.60658281545735 -322.1122825558911
82.84777739062326 -172.07675649628214
-33.22067267862173 -67.0260432642205
22.928444661056417 -201.76612966376484
74.5060002792926 -322.26398401291976
16.323379277034476 -137.4758587314786
9.293117815969566 -220.94098174233622
-7.87092541373724 -247.61839487504488
59.426532716410236 -198.4789914438825
26.733959523463398 -15.416869928034657
43.95498524823793 -179.21625900783835
8.311958207855369 -251.6459395341446
53.01355085309157 -306.66817102777327
-4.347452735959337 -151.8955178265575
35.492783479688114 -69.40349433086988
0.07495244567130044 -48.924136756099244
-6.3551705920123 -292.63331459583617
1.1705497354754755 -280.45114637974973
-75.24459979727588 -347.3087594726496
54.93765202759468 -343.6010217758326
-34.17004028667481 -356.1954160700987
-72.82674236713252 -113.07576798617515
-11.403687571256611 -25.669778653465755
37.15957159885626 -181.924159667751
44.60051728564835 -19.505178474175125
-19.39123664316378 -319.9186149964883
42.124174510697 -238.0063602499967
-25.10066088590864 -112.27374382495631
20.86142297230296 -308.89605846327856
52.19777532724089 -298.64568929299315
1.3221813545369798 -262.50877199230956
1.2803719505300535 -238.8090361489136
-71.6503219393951 -192.67040405676957
-56.14986678059176 -305.88182291429035
-56.01910899882317 -172.23965663551255
6.2356935351999425 -107.0720986868235
-8.839513460872354 -300.22394267725156
81.92097847914866 -321.11712867291743
-20.720397668332367 -290.48833529074653
-57.8727582516039 -9.225593780300073
28.111446481285597 -285.6326681426428
-82.0528812041521 -171.11487219245433
-15.330839025828368 -137.40988917570462
-6.787874140930924 -231.22128079958776
-77.21073291170313 -88.96955330001833
69.61323711712575 -49.59117865436883
-19.011435167530493 -215.2425747172486
-56.64499273390181 -185.49476199436464
2.4916814254542317 -175.09966529861168
68.01093721590988 -145.04160740958875
-2.90064491833337 -215.40404271916842
-83.65404552806584 -30.97894277414497
73.54454579026333 -124.81682682608226
-87.7054298798591 -17.95393896512502
86.75214877212062 -271.2370640452662
-66.70296268769859 -15.886560483667779
40.101748200949345 -354.95512701168025
50.527903480566835 -212.49373189980707
-89.01536415884328 -258.7145681859705
55.81343411979236 -83.32073723669299
19.19172039602617 -52.66709082807796
-89.87815857423224 -343.47294544020076
5.581267293231363 -198.85678551631477
-64.08819169532924 -48.549834641000814
66.23687218224981 -237.04447771096335
-62.415904451103216 -197.41464235003434
-21.134013645717914 -287.026186448
37.10298956654108 -158.2873010412735
-3.0488620160675453 -232.1859850788897
-67.09903690169799 -10.859127207113659
-41.817163100787745 -323.840322845981
-28.39832720552083 -339.82605634846647
52.79994978190234 -263.0060125245925
-56.24560730823439 -141.817271193722
53.688804330178215 -350.4949455887163
-37.240678699611976 -83.50577771796321
-88.66824949780447 -358.5067937341035
46.49692992930903 -335.36537018575183
9.33496778322889 -301.3828196529803
-87.18555915392277 -127.28980896945941
79.61208339004799 -172.21509184527122
-71.56330787113045 -173.6429272116652
-75.31073478741573 -27.45534937904239
-26.65141293781666 -79.13131522295669
-40.29533816724038 -152.90379352722454
-77.86862361718778 -82.96196963278021
13.382220011927359 -122.61152410918152
-68.26466830751066 -63.12823979159174
27.799635109045113 -62.37503393574161
40.781491125644976 -143.84076355929383
-54.09360781489601 -140.42682194886504
-36.536934806432825 -162.88142864994106
33.5662217053147 -278.0119851727583
44.85322474415949 -254.66680480014827
-48.24699084634565 -195.48757435846505
-31.57142854258825 -30.787736260478084
-2.2434112978683487 -313.52942416448434
86.83530874226881 -9.402734240625364
31.24231878553529 -225.05355318209297
36.83164414130064 -235.42781828495038
-15.026983671285507 -109.09717216512573
2.928550129156122 -125.7346871876438
67.95683737298185 -210.1064467040539
6.31386806712581 -191.11707797217568
-85.30113368972665 -295.1332604489372
44.97804369257594 -120.71798565137138
81.32691454647684 -210.77900508700108
-45.22927383378383 -84.12877375378145
63.18602199060405 -271.26265509661175
50.366580294741624 -336.61190791849157
80.18195290564043 -14.609222312307509
-72.33674318958138 -85.90163056039552
-63.61803275389168 -209.68815641202434
-83.53660489923472 -222.92776981278806

In [5]:
from citipy import citipy

In [6]:
# Create a list for holding the cities.
cities = []

# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    #if the city is unique, add it to the list
    if city not in cities:
        cities.append(city)
        
#print the city count to confirm sufficient count
len(cities)

271

In [7]:
# Import the requests library.
import requests

# Import the API key.
from config import weather_api_key

In [8]:
# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

In [10]:
# Starting URL for Weather Map API Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

In [11]:
#create an empty list to hold the city data
city_data = []

#print the beginning of the logging
print("Beginning Data Retrieval       ")
print("-------------------------------")

#create counters
record_count = 1
set_count = 1

# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    
    # Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-------------------------------
Processing Record 1 of Set 1 | narsaq
Processing Record 2 of Set 1 | mys shmidta
City not found. Skipping...
Processing Record 3 of Set 1 | egvekinot
Processing Record 4 of Set 1 | provideniya
Processing Record 5 of Set 1 | axim
Processing Record 6 of Set 1 | vaini
Processing Record 7 of Set 1 | jamestown
Processing Record 8 of Set 1 | punta arenas
Processing Record 9 of Set 1 | halalo
City not found. Skipping...
Processing Record 10 of Set 1 | mataura
Processing Record 11 of Set 1 | vaitupu
City not found. Skipping...
Processing Record 12 of Set 1 | tabou
Processing Record 13 of Set 1 | qaanaaq
Processing Record 14 of Set 1 | morrope
Processing Record 15 of Set 1 | rikitea
Processing Record 16 of Set 1 | georgetown
Processing Record 17 of Set 1 | ushuaia
Processing Record 18 of Set 1 | puerto baquerizo moreno
Processing Record 19 of Set 1 | atuona
Processing Record 20 of Set 1 | faanui
Processing Record 21 of Set 1 | saint george
Processing Record 22 of Set 1 | arraial do cabo
Processing Record 23 of Set 1 | nouadhibou
Processing Record 24 of Set 1 | illoqqortoormiut
City not found. Skipping...
Processing Record 25 of Set 1 | torbay
Processing Record 26 of Set 1 | thompson
Processing Record 27 of Set 1 | the valley
Processing Record 28 of Set 1 | ribeira grande
Processing Record 29 of Set 1 | codajas
Processing Record 30 of Set 1 | chuy
Processing Record 31 of Set 1 | uarini
Processing Record 32 of Set 1 | attawapiskat
City not found. Skipping...
Processing Record 33 of Set 1 | san patricio
Processing Record 34 of Set 1 | puerto ayora
Processing Record 35 of Set 1 | kodiak
Processing Record 36 of Set 1 | norman wells
Processing Record 37 of Set 1 | yellowknife
Processing Record 38 of Set 1 | dingle
Processing Record 39 of Set 1 | camocim
Processing Record 40 of Set 1 | constitucion
Processing Record 41 of Set 1 | ilulissat
Processing Record 42 of Set 1 | havre
Processing Record 43 of Set 1 | la plaine
Processing Record 44 of Set 1 | rocha
Processing Record 45 of Set 1 | panama city
Processing Record 46 of Set 1 | tetlanohcan
Processing Record 47 of Set 1 | dolores
Processing Record 48 of Set 1 | mirandela
Processing Record 49 of Set 1 | port hardy
Processing Record 50 of Set 1 | laguna
Processing Record 1 of Set 2 | cape town
Processing Record 2 of Set 2 | upernavik
Processing Record 3 of Set 2 | klaksvik
Processing Record 4 of Set 2 | lompoc
Processing Record 5 of Set 2 | rondonopolis
Processing Record 6 of Set 2 | paamiut
Processing Record 7 of Set 2 | hilo
Processing Record 8 of Set 2 | escarcega
Processing Record 9 of Set 2 | moerai
Processing Record 10 of Set 2 | sunrise manor
Processing Record 11 of Set 2 | mar del plata
Processing Record 12 of Set 2 | sidi ali
Processing Record 13 of Set 2 | barentsburg
City not found. Skipping...
Processing Record 14 of Set 2 | kapaa
Processing Record 15 of Set 2 | labelle
Processing Record 16 of Set 2 | lebu
Processing Record 17 of Set 2 | salinas
Processing Record 18 of Set 2 | levittown
Processing Record 19 of Set 2 | high rock
Processing Record 20 of Set 2 | matagami
Processing Record 21 of Set 2 | makakilo city
Processing Record 22 of Set 2 | clyde river
Processing Record 23 of Set 2 | cabedelo
Processing Record 24 of Set 2 | fortuna
Processing Record 25 of Set 2 | lufilufi
Processing Record 26 of Set 2 | caravelas
Processing Record 27 of Set 2 | gao
Processing Record 28 of Set 2 | westerly
Processing Record 29 of Set 2 | port hawkesbury
Processing Record 30 of Set 2 | avarua
Processing Record 31 of Set 2 | san francisco
Processing Record 32 of Set 2 | halifax
Processing Record 33 of Set 2 | dauphin
Processing Record 34 of Set 2 | saldanha
Processing Record 35 of Set 2 | tuktoyaktuk
Processing Record 36 of Set 2 | papara
Processing Record 37 of Set 2 | castro
Processing Record 38 of Set 2 | muros
Processing Record 39 of Set 2 | fort nelson
Processing Record 40 of Set 2 | touros
Processing Record 41 of Set 2 | cacoal
Processing Record 42 of Set 2 | cervo
Processing Record 43 of Set 2 | senneterre
Processing Record 44 of Set 2 | cidreira
Processing Record 45 of Set 2 | rio gallegos
Processing Record 46 of Set 2 | ojinaga
Processing Record 47 of Set 2 | louisbourg
City not found. Skipping...
Processing Record 48 of Set 2 | araouane
Processing Record 49 of Set 2 | worland
Processing Record 50 of Set 2 | luderitz
Processing Record 1 of Set 3 | marcona
City not found. Skipping...
Processing Record 2 of Set 3 | high level
Processing Record 3 of Set 3 | maceio
Processing Record 4 of Set 3 | moron
Processing Record 5 of Set 3 | nanortalik
Processing Record 6 of Set 3 | husavik
Processing Record 7 of Set 3 | ashland
Processing Record 8 of Set 3 | hermanus
Processing Record 9 of Set 3 | tasiilaq
Processing Record 10 of Set 3 | olafsvik
Processing Record 11 of Set 3 | san luis
Processing Record 12 of Set 3 | aguimes
Processing Record 13 of Set 3 | hamilton
Processing Record 14 of Set 3 | soure
Processing Record 15 of Set 3 | olinda
Processing Record 16 of Set 3 | vila franca do campo
Processing Record 17 of Set 3 | ixtapa
Processing Record 18 of Set 3 | fairbanks
Processing Record 19 of Set 3 | saint-francois
Processing Record 20 of Set 3 | coquimbo
Processing Record 21 of Set 3 | cabo san lucas
Processing Record 22 of Set 3 | sitka
Processing Record 23 of Set 3 | redmond
Processing Record 24 of Set 3 | flin flon
Processing Record 25 of Set 3 | manicore
Processing Record 26 of Set 3 | saquena
Processing Record 27 of Set 3 | muisne
Processing Record 28 of Set 3 | iberia
Processing Record 29 of Set 3 | bolgatanga
Processing Record 30 of Set 3 | nantucket
Processing Record 31 of Set 3 | rosarito
Processing Record 32 of Set 3 | boa esperanca
Processing Record 33 of Set 3 | fernley
Processing Record 34 of Set 3 | bethel
Processing Record 35 of Set 3 | barrow
Processing Record 36 of Set 3 | isla mujeres
Processing Record 37 of Set 3 | tougan
Processing Record 38 of Set 3 | cockburn town
Processing Record 39 of Set 3 | chicama
Processing Record 40 of Set 3 | havre-saint-pierre
Processing Record 41 of Set 3 | kahului
Processing Record 42 of Set 3 | camapua
Processing Record 43 of Set 3 | mercedes
Processing Record 44 of Set 3 | itabira
Processing Record 45 of Set 3 | pau brasil
Processing Record 46 of Set 3 | santa cruz
Processing Record 47 of Set 3 | alcantara
Processing Record 48 of Set 3 | jacareacanga
Processing Record 49 of Set 3 | grindavik
Processing Record 50 of Set 3 | geraldton
Processing Record 1 of Set 4 | bubaque
Processing Record 2 of Set 4 | adrar
Processing Record 3 of Set 4 | lampazos de naranjo
Processing Record 4 of Set 4 | pacifica
Processing Record 5 of Set 4 | sechura
Processing Record 6 of Set 4 | san javier
Processing Record 7 of Set 4 | marsh harbour
Processing Record 8 of Set 4 | belmonte
Processing Record 9 of Set 4 | sao filipe
Processing Record 10 of Set 4 | hofn
Processing Record 11 of Set 4 | pochutla
Processing Record 12 of Set 4 | bell ville
Processing Record 13 of Set 4 | saint-pierre
Processing Record 14 of Set 4 | coahuayana
Processing Record 15 of Set 4 | mineiros
Processing Record 16 of Set 4 | hualmay
Processing Record 17 of Set 4 | indiaroba
Processing Record 18 of Set 4 | brae
Processing Record 19 of Set 4 | necochea
Processing Record 20 of Set 4 | pontes e lacerda
Processing Record 21 of Set 4 | rawson
Processing Record 22 of Set 4 | sao geraldo do araguaia
Processing Record 23 of Set 4 | acapulco
Processing Record 24 of Set 4 | bathsheba
Processing Record 25 of Set 4 | coihaique
Processing Record 26 of Set 4 | samusu
City not found. Skipping...
Processing Record 27 of Set 4 | pangai
Processing Record 28 of Set 4 | codrington
Processing Record 29 of Set 4 | lagoa
Processing Record 30 of Set 4 | grand island
Processing Record 31 of Set 4 | north bend
Processing Record 32 of Set 4 | tautira
Processing Record 33 of Set 4 | progreso
Processing Record 34 of Set 4 | ponta do sol
Processing Record 35 of Set 4 | imbituba
Processing Record 36 of Set 4 | boa vista
Processing Record 37 of Set 4 | tomatlan
Processing Record 38 of Set 4 | grand centre
City not found. Skipping...
Processing Record 39 of Set 4 | porto novo

Processing Record 40 of Set 4 | barstow
Processing Record 41 of Set 4 | stromness
Processing Record 42 of Set 4 | la brea
Processing Record 43 of Set 4 | tecolutla
Processing Record 44 of Set 4 | hastings
Processing Record 45 of Set 4 | belize
Processing Record 46 of Set 4 | diego de almagro
Processing Record 47 of Set 4 | inhumas
Processing Record 48 of Set 4 | nanakuli
Processing Record 49 of Set 4 | santa maria da boa vista
Processing Record 50 of Set 4 | sao desiderio
Processing Record 1 of Set 5 | puerto madryn
Processing Record 2 of Set 5 | wiarton
Processing Record 3 of Set 5 | valparaiso
Processing Record 4 of Set 5 | praia da vitoria
Processing Record 5 of Set 5 | enid
Processing Record 6 of Set 5 | goderich
Processing Record 7 of Set 5 | villazon
Processing Record 8 of Set 5 | san cristobal
Processing Record 9 of Set 5 | gillette
Processing Record 10 of Set 5 | semme
Processing Record 11 of Set 5 | pisco
Processing Record 12 of Set 5 | camana
Processing Record 13 of Set 5 | posse
Processing Record 14 of Set 5 | ilhabela
Processing Record 15 of Set 5 | marienburg
Processing Record 16 of Set 5 | aklavik
Processing Record 17 of Set 5 | kolda
Processing Record 18 of Set 5 | taos
Processing Record 19 of Set 5 | santa fe
Processing Record 20 of Set 5 | pacific grove
Processing Record 21 of Set 5 | bernalillo
Processing Record 22 of Set 5 | taltal
Processing Record 23 of Set 5 | comodoro rivadavia
Processing Record 24 of Set 5 | ancud
Processing Record 25 of Set 5 | groton
Processing Record 26 of Set 5 | cayenne
Processing Record 27 of Set 5 | barcelos
Processing Record 28 of Set 5 | point fortin
Processing Record 29 of Set 5 | moctezuma
Processing Record 30 of Set 5 | santa maria
Processing Record 31 of Set 5 | sao jose da coroa grande
Processing Record 32 of Set 5 | mulege
Processing Record 33 of Set 5 | sao borja
Processing Record 34 of Set 5 | eureka
Processing Record 35 of Set 5 | mayo
Processing Record 36 of Set 5 | kenai
Processing Record 37 of Set 5 | palmer
Processing Record 38 of Set 5 | riberalta
Processing Record 39 of Set 5 | kirkwall
Processing Record 40 of Set 5 | los llanos de aridane
Processing Record 41 of Set 5 | nova olinda do norte
Processing Record 42 of Set 5 | sao joao da barra
Processing Record 43 of Set 5 | gimli
Processing Record 44 of Set 5 | crawfordsville
Processing Record 45 of Set 5 | alta floresta
Processing Record 46 of Set 5 | raudeberg
Processing Record 47 of Set 5 | acarau
Processing Record 48 of Set 5 | marlton
Processing Record 49 of Set 5 | sioux lookout
Processing Record 50 of Set 5 | huarmey
Processing Record 1 of Set 6 | puerto escondido
Processing Record 2 of Set 6 | carballo
Processing Record 3 of Set 6 | marquette
Processing Record 4 of Set 6 | west richland
Processing Record 5 of Set 6 | lexington
Processing Record 6 of Set 6 | girvan
Processing Record 7 of Set 6 | henderson
Processing Record 8 of Set 6 | ocala
Processing Record 9 of Set 6 | poquoson
Processing Record 10 of Set 6 | barauna
Processing Record 11 of Set 6 | saint-georges
Processing Record 12 of Set 6 | prince george
Processing Record 13 of Set 6 | douentza
Processing Record 14 of Set 6 | sidney
Processing Record 15 of Set 6 | vestmannaeyjar
Processing Record 16 of Set 6 | moffat
Processing Record 17 of Set 6 | japura
Processing Record 18 of Set 6 | capiibary
Processing Record 19 of Set 6 | graham
Processing Record 20 of Set 6 | sinnamary
Processing Record 21 of Set 6 | hay river
-----------------------------
Data Retrieval Complete
-----------------------------

In [13]:
len(city_data)

261

In [14]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Narsaq,60.9167,-46.0500,43.02,78,99,5.82,GL,2022-11-14 21:20:16
1,Egvekinot,66.3167,-179.1667,10.63,97,100,2.73,RU,2022-11-14 21:20:17
2,Provideniya,64.3833,-173.3000,28.51,59,100,13.00,RU,2022-11-14 21:20:17
3,Axim,4.8699,-2.2405,78.91,84,100,7.25,GH,2022-11-14 21:20:17
4,Vaini,-21.2000,-175.2000,78.96,83,75,9.22,TO,2022-11-14 21:20:18
5,Jamestown,42.0970,-79.2353,34.72,71,100,1.99,US,2022-11-14 21:20:18
6,Punta Arenas,-53.1500,-70.9167,57.31,67,75,5.75,CL,2022-11-14 21:20:19
7,Mataura,-46.1927,168.8643,58.48,52,7,2.91,NZ,2022-11-14 21:20:19
8,Tabou,4.4230,-7.3528,78.06,83,100,6.15,CI,2022-11-14 21:20:20
9,Qaanaaq,77.4840,-69.3632,-4.81,67,9,7.14,GL,2022-11-14 21:20:21

In [16]:
new_column_order = ["City", "Country", "Date", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed"]
city_data_df = city_data_df[new_column_order]
city_data_df.head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,Narsaq,GL,2022-11-14 21:20:16,60.9167,-46.0500,43.02,78,99,5.82
1,Egvekinot,RU,2022-11-14 21:20:17,66.3167,-179.1667,10.63,97,100,2.73
2,Provideniya,RU,2022-11-14 21:20:17,64.3833,-173.3000,28.51,59,100,13.00
3,Axim,GH,2022-11-14 21:20:17,4.8699,-2.2405,78.91,84,100,7.25
4,Vaini,TO,2022-11-14 21:20:18,-21.2000,-175.2000,78.96,83,75,9.22
5,Jamestown,US,2022-11-14 21:20:18,42.0970,-79.2353,34.72,71,100,1.99
6,Punta Arenas,CL,2022-11-14 21:20:19,-53.1500,-70.9167,57.31,67,75,5.75
7,Mataura,NZ,2022-11-14 21:20:19,-46.1927,168.8643,58.48,52,7,2.91
8,Tabou,CI,2022-11-14 21:20:20,4.4230,-7.3528,78.06,83,100,6.15
9,Qaanaaq,GL,2022-11-14 21:20:21,77.4840,-69.3632,-4.81,67,9,7.14

In [17]:
# Create the output file (CSV).
output_data_file = "weather_data/cities.csv"
# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")